In [1]:
"""
 Write a python program for following tasks - 
Make sure all the required libraries are imported at the beginning of the Jupyter Notebook.
 a)Load the windpower dataset into the notebook.
 b)Check records for any missing values and remove them permanently using appropriate method.
 c)Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and 
testing (25%) sets using random state of 42.
 d)Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.
 e)Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of determinaon) for 
each polynomial degree.
 f)Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot 
accordingly.
 g)Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.
 h)Print the coefficients and intercept for each trained polynomial regression model.
 i)Use each model to predict power output for wind speeds of 5, 10, 15, and 20 m/s, and print the predic ons
"""

'\n Write a python program for following tasks - \nMake sure all the required libraries are imported at the beginning of the Jupyter Notebook.\n a)Load the windpower dataset into the notebook.\n b)Check records for any missing values and remove them permanently using appropriate method.\n c)Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and \ntesting (25%) sets using random state of 42.\n d)Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.\n e)Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of determinaon) for \neach polynomial degree.\n f)Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot \naccordingly.\n g)Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.\n h)Print the coefficients and intercept for each trained polynomial regression model.\n i)Use each model to predict power output for wind speeds of 5, 10, 15, and 20 m/s, and print the predic ons\n'

In [8]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures


df = pd.read_csv("D:\dvc\py\csv files\windpower.csv")
df

     Power (kW)  Wind speed (m/s)
0           0.0             0.000
1           0.0             0.125
2           0.0             0.150
3           0.0             0.225
4           0.0             0.275
..          ...               ...
495         0.0            24.775
496         0.0            24.850
497         0.0            24.875
498         0.0            24.950
499         0.0            25.000

[500 rows x 2 columns]

In [9]:
df.info()
print("misiing values = \n" ,df.isna().sum())
df = df.dropna()
print("missing values = \n", df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Power (kW)        497 non-null    float64
 1   Wind speed (m/s)  495 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB
misiing values =
 Power (kW)          3
Wind speed (m/s)    5
dtype: int64
missing values =
 Power (kW)          0
Wind speed (m/s)    0
dtype: int64

In [10]:
x = df[["Power (kW)"]]
y =df["Wind speed (m/s)"]
print(y)
x

0       0.000
1       0.125
2       0.150
3       0.225
4       0.275
        ...
495    24.775
496    24.850
497    24.875
498    24.950
499    25.000
Name: Wind speed (m/s), Length: 492, dtype: float64

     Power (kW)
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
..          ...
495         0.0
496         0.0
497         0.0
498         0.0
499         0.0

[492 rows x 1 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.75, random_state=42)