In [21]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("D:\dvc\py\csv files\Employee_Attrition.csv")
df.info()
print(df.isna().sum())
df.head()

# drop the col
df.drop(columns="Employee_ID", inplace=True)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         250 non-null    int64
 1   Age                 250 non-null    int64
 2   Monthly_Income      250 non-null    int64
 3   Years_at_Company    250 non-null    int64
 4   Job_Role            250 non-null    object
 5   Work_Life_Balance   250 non-null    object
 6   Overtime            250 non-null    object
 7   Job_Satisfaction    250 non-null    int64
 8   Distance_From_Home  250 non-null    int64
 9   Education           250 non-null    object
 10  Attrition           250 non-null    int64
dtypes: int64(7), object(4)
memory usage: 21.6+ KB
Employee_ID           0
Age                   0
Monthly_Income        0
Years_at_Company      0
Job_Role              0
Work_Life_Balance     0
Overtime              0
Job_Satisfaction      0
Distance_From_Home    0
Education             0
Attrition             0
dtype: int64

,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,56,31395,18,HR,Poor,Yes,1,7,School,1
2,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,39,20851,5,HR,Good,No,2,7,Graduate,0
4,28,32156,12,Developer,Good,No,3,26,School,0

In [22]:
x = df.iloc[:,0:9]
y = df["Attrition"]

x = pd.get_dummies(x, drop_first=True)

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.8, random_state=42)
print("x train dataset number = " , x_train.shape[0])
print("x test dataset number = " , x_test.shape[0])
print("y train dataset number = " , y_train.shape[0])
print("y test dataset number = " , y_test.shape[0])

knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

print("confusion matrix = \n", confusion_matrix(y_test, y_pred))
print("accuracy_score = ", accuracy_score(y_test, y_pred))
print("classifcation report = ", classification_report(y_test, y_pred))

x train dataset number =  200
x test dataset number =  50
y train dataset number =  200
y test dataset number =  50
confusion matrix =
 [[47  0]
 [ 3  0]]
accuracy_score =  0.94
classifcation report =                precision    recall  f1-score   support

           0       0.94      1.00      0.97        47
           1       0.00      0.00      0.00         3

    accuracy                           0.94        50
   macro avg       0.47      0.50      0.48        50
weighted avg       0.88      0.94      0.91        50

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [23]:
# if the question ask to optimise and get the highest accuracy score from the give "k" neighbour nodes = then put main LOC inside the for loop 
acc_score_list = []
for k in range(1,26):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    acc_score_list.append(acc)
    print(f"k = {k} and Accuracy = {acc}")

max_acc = max(acc_score_list)
best_k = (acc_score_list.index(max_acc)) + 1 # +1 becasue the index of list start with 0 and we want k=2 which has the highest accuracy and it is sitting at index number 1 
print(best_k)
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

print("confusion_matrix = \n", confusion_matrix(y_test, y_pred))
print("accuracy score = ",accuracy_score(y_test, y_pred))
print("classification_report = ", classification_report(y_test, y_pred))

k = 1 and Accuracy = 0.86
k = 2 and Accuracy = 0.94
k = 3 and Accuracy = 0.94
k = 4 and Accuracy = 0.94
k = 5 and Accuracy = 0.94
k = 6 and Accuracy = 0.94
k = 7 and Accuracy = 0.94
k = 8 and Accuracy = 0.94
k = 9 and Accuracy = 0.94
k = 10 and Accuracy = 0.94
k = 11 and Accuracy = 0.94
k = 12 and Accuracy = 0.94
k = 13 and Accuracy = 0.94
k = 14 and Accuracy = 0.94
k = 15 and Accuracy = 0.94
k = 16 and Accuracy = 0.94
k = 17 and Accuracy = 0.94
k = 18 and Accuracy = 0.94
k = 19 and Accuracy = 0.94
k = 20 and Accuracy = 0.94
k = 21 and Accuracy = 0.94
k = 22 and Accuracy = 0.94
k = 23 and Accuracy = 0.94
k = 24 and Accuracy = 0.94
k = 25 and Accuracy = 0.94
2
confusion_matrix =
 [[47  0]
 [ 3  0]]
accuracy score =  0.94
classification_report =                precision    recall  f1-score   support

           0       0.94      1.00      0.97        47
           1       0.00      0.00      0.00         3

    accuracy                           0.94        50
   macro avg       0.47      0.50      0.48        50
weighted avg       0.88      0.94      0.91        50

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [20]:
rf = RandomForestClassifier(n_estimators=150, max_depth=12, criterion="entropy", random_state=42)
rf.fit(x_train, y_train)
y_pred1 = rf.predict(x_test)
print("RF confusion_matrix = \n", confusion_matrix(y_test, y_pred1))
print("RF accuracy score = ",accuracy_score(y_test, y_pred1))
print("RF classification_report = ", classification_report(y_test, y_pred1))

RF confusion_matrix =
 [[47  0]
 [ 1  2]]
RF accuracy score =  0.98
RF classification_report =                precision    recall  f1-score   support

           0       0.98      1.00      0.99        47
           1       1.00      0.67      0.80         3

    accuracy                           0.98        50
   macro avg       0.99      0.83      0.89        50
weighted avg       0.98      0.98      0.98        50

In [25]:
x

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
0,29,23278,8,1,22,False,False,True,False,True,True,True,False
1,56,31395,18,1,7,False,True,False,False,True,True,False,True
2,54,98907,0,2,15,False,False,True,False,False,False,True,False
3,39,20851,5,2,7,False,True,False,True,False,False,False,False
4,28,32156,12,3,26,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,46,39369,7,2,1,True,False,False,False,False,True,False,False
246,42,74890,4,4,17,False,True,False,False,False,True,True,False
247,52,116447,1,3,22,False,False,True,False,False,True,False,False
248,55,69391,10,3,22,False,False,True,True,False,False,True,False
249,38,99963,15,3,8,False,False,True,False,True,False,False,False

In [28]:
x_sample = np.array([30, 45000, 5, 3, 10, 1, 0,0,1,0,1,0,0]).reshape(1,-1)
print("predicition in knn model",  knn.predict(x_sample)) # answer is [0] meaning that the employee will not leave the job...
print("predicition in RF model",  rf.predict(x_sample))

predicition in knn model [0]
predicition in RF model [0]

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(